language: ruby
rvm:
  - 2.2

sudo: false

branches:
  only:
    - master

cache:
  bundler: true
  directories:
    - node_modules # NPM packages
    # - dist/assets/images # optimized images

addons:
  ssh_known_hosts: s210904.gridserver.com
  apt_packages:
    - graphicsmagick

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - . $HOME/.nvm/nvm.sh && nvm install 4.4 && nvm use 4.4
  - npm install

script: gulp build --prod

before_deploy:
  - openssl aes-256-cbc -K $encrypted_f55b475b43f3_key -iv $encrypted_f55b475b43f3_iv -in deploy_keys.tar.enc -out /tmp/deploy_keys.tar -d
  - tar -xvf /tmp/deploy_keys.tar -C /tmp/
  - mv /tmp/rsync-credentials.json rsync-credentials.json
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/id_rsa
  - ssh-add /tmp/id_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: gulp deploy
  on:
    branch: master
